#!/usr/bin/perl
package rhich;
use strict;
use warnings;
use vars qw($VERSION);

$VERSION = '1.002';

=encoding utf8

=head1 NAME

rhich - which(1) with a regex

=head1 SYNOPSIS

Run this program like you would which(1), but give is a regex. Even
a sequence is a regex.

	% rhich perl
	% rhich p*rl

=head1 DESCRIPTION

rhich(1) goes through the directories listed in PATH and lists files
that match the regular expression given sas the argument.

=head1 COPYRIGHT AND LICENCE

Copyright © 2013-2015, brian d foy <bdfoy@cpan.org>. All rights reserved.

You may use this under the same terms as Perl itself.

=head1 AUTHOR

brian d foy, C<< <bdfoy@cpan.org> >>

=cut

use App::rhich;

App::rhich::run();
